sync:
  - source: graphgen
    dest: graphgen
  - source: resources/nltk_data
    dest: resources/nltk_data
  - source: resources/examples
    dest: resources/examples
  - source: webui
    dest: webui
  - source: webui/app.py
    dest: app.py
  - source: requirements.txt
    dest: requirements.txt
  - source: LICENSE
    dest: LICENSE
