input_data_type: raw # raw, chunked
input_file: resources/input_examples/raw_demo.jsonl  # input file path, support json, jsonl, txt. See resources/input_examples for examples
output_data_type: cot # atomic, aggregated, multi_hop, cot
output_data_format: Sharegpt # Alpaca, Sharegpt, ChatML
tokenizer: cl100k_base # tokenizer for counting tokens, support tiktoken tokenizer names and local tokenizer path
search: # web search configuration
  enabled: false # whether to enable web search
  search_types: ["google"] # search engine types, support: google, bing, uniprot, wikipedia
method_params:
  method: leiden
  max_size: 20 # Maximum size of communities
  use_lcc: false
  random_seed: 42
